-- Users table is automatically managed by Supabase Auth.
-- We add a "name" column that mirrors the metadata provided at sign-up.
alter table auth.users add column if not exists name text;

-- Products
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  short_name text,
  price integer not null,
  category text not null,
  description text,
  features text,
  images jsonb,
  included_items jsonb,
  gallery jsonb
);

-- Orders
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete set null,
  total integer not null,
  created_at timestamp with time zone default now()
);

-- Cart items per order (snapshot of cart at purchase time)
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders on delete cascade,
  product_id bigint references public.products,
  quantity integer not null,
  unit_price integer not null
);

-- RLS: allow logged-in users to see their own orders & order_items.
-- Feel free to enable additional policies in Supabase dashboard.
